package com.github.mihowjingle.cartographer.model.objects

import com.github.mihowjingle.cartographer.model.common.Position
import com.github.mihowjingle.cartographer.model.common.Rotation

data class Megalith(
    val name: String,
    val type: Type,
    val position: Position,
    val ownerPlayerIndex: Int,
    val rotation: Rotation,
    val numberOfShips: Int = 0,
    val createInHyperspace: Boolean = false
) : Entity {

    override fun toLua(): String {
        val createInHyperspaceDigit = if (createInHyperspace) 1 else 0
        return "addSquadron(\"$name\", \"${type.label}\", {${position.x}, ${position.z}, ${position.y}}, $ownerPlayerIndex, " +
                "{${rotation.xAxis}, ${rotation.zAxis}, ${rotation.yAxis}}, $numberOfShips, $createInHyperspaceDigit)"
    }

    enum class Type(val label: String) {
        MEGALITH_1("meg_asteroid"),
        MEGALITH_2("meg_asteroid_nosubs"),
        MEGALITH_3("meg_asteroid_mp"),
        MEGALITH_4("meg_balcoragate"),
        MEGALITH_5("meg_bentus"),
        MEGALITH_6("meg_bentus_ruin_1"),
        MEGALITH_7("meg_bentus_ruin_2"),
        MEGALITH_8("meg_bentus_ruin_3"),
        MEGALITH_9("meg_bentus_ruin_4"),
        MEGALITH_10("meg_bentus_ruin_5"),
        MEGALITH_12("meg_bentus_ruin_6"),
        MEGALITH_13("meg_bentus_ruin_7"),
        MEGALITH_14("meg_bentus_ruin_8"),
        MEGALITH_15("meg_bentus_ruin_9"),
        MEGALITH_16("meg_bentus_ruin_10"),
        MEGALITH_17("meg_bentus_ruin_11"),
        MEGALITH_18("meg_bentus_ruined"),
        MEGALITH_19("meg_bentus_ruins_core_1"),
        MEGALITH_20("meg_bentus_ruins_core_2"),
        MEGALITH_21("meg_bentus_ruins_core_3"),
        MEGALITH_22("meg_bigred"),
        MEGALITH_23("meg_chimera"),
        MEGALITH_24("meg_dreadnaughtberth"),
        MEGALITH_25("meg_foundry"),
        MEGALITH_26("meg_foundrydebris_chunk1"),
        MEGALITH_27("meg_foundrydebris_chunk2"),
        MEGALITH_28("meg_foundrydebris_chunk3"),
        MEGALITH_29("meg_foundrydebris_chunk4"),
        MEGALITH_30("meg_foundrydebris_flake1"),
        MEGALITH_31("meg_foundrydebris_flake2"),
        MEGALITH_32("meg_foundrydebris_flake3"),
        MEGALITH_33("meg_foundrydebris_flake4"),
        MEGALITH_34("meg_gehenna_1"),
        MEGALITH_35("meg_gehenna_2"),
        MEGALITH_36("meg_gehenna_3"),
        MEGALITH_37("meg_gehenna_4"),
        MEGALITH_38("meg_gehenna_5"),
        MEGALITH_39("meg_gehenna_6"),
        MEGALITH_40("meg_gehenna_7"),
        MEGALITH_41("meg_misslefrigate"),
        MEGALITH_42("meg_progenitorpowermodule"),
        MEGALITH_43("meg_progenitorpowertrigger"),
        MEGALITH_44("meg_progenitorpowertrigger_noui"),
        MEGALITH_45("meg_sajhulknose"),
        MEGALITH_46("meg_sajhulknose_ui"),
        MEGALITH_47("meg_sajhulkpanels"),
        MEGALITH_48("meg_sajhulkpanels_ui"),
        MEGALITH_49("meg_sajhulkturret"),
        MEGALITH_50("meg_salvagecollector"),
        MEGALITH_51("meg_tanis"),
        MEGALITH_52("meg_tanisstructure_medium"),
        MEGALITH_53("meg_tanisstructure_medium2"),
        MEGALITH_54("meg_veildebris_bit1"),
        MEGALITH_55("meg_veildebris_bit2"),
        MEGALITH_56("meg_veildebris_bit3"),
        MEGALITH_57("meg_veildebris_bit4"),
        MEGALITH_58("meg_veildebris_bit5"),
        MEGALITH_59("meg_veildebris_bit6"),
        MEGALITH_60("meg_veildebris_bit7"),
        MEGALITH_61("meg_veildebris_bit8"),
        MEGALITH_62("meg_veildebris_bit9"),
        MEGALITH_63("meg_veildebris_bit10"),
        MEGALITH_64("meg_veildebris_bit11"),
        MEGALITH_65("meg_veildebris_bit12"),
        MEGALITH_66("meg_veildebris_bit13"),
        MEGALITH_67("meg_veildebris_bit14"),
        MEGALITH_68("meg_veildebris_bit15"),
        MEGALITH_69("meg_veildebris_chunk1"),
        MEGALITH_70("meg_veildebris_chunk2"),
        MEGALITH_71("meg_veildebris_chunk3"),
        MEGALITH_72("meg_veildebris_chunk4"),
        MEGALITH_73("meg_veildebris_chunk5"),
        MEGALITH_74("meg_veildebris_chunk1_nd"),
        MEGALITH_75("meg_veildebris_chunk2_nd"),
        MEGALITH_76("meg_veildebris_chunk3_nd"),
        MEGALITH_77("meg_veildebris_chunk4_nd"),
        MEGALITH_78("meg_veildebris_chunk5_nd"),
        MEGALITH_79("meg_veildebris_chunk_lighthouse"),
        MEGALITH_80("meg_veildebris_flake1"),
        MEGALITH_81("meg_veildebris_flake2"),
        MEGALITH_82("meg_veildebris_flake3"),
        MEGALITH_83("meg_veildebris_flake4"),
        MEGALITH_84("meg_veildebris_flake5"),
        MEGALITH_85("meg_veildebris_flake6"),
        MEGALITH_86("meg_veildebris_flake7"),
        MEGALITH_87("meg_veildebris_flake8"),
        MEGALITH_88("meg_veildebris_flake9"),
        MEGALITH_89("meg_veildebris_flake10")
    }
}